policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      dco: true
      gpg:
        required: false
        identity:
          gitHubOrganization: some-organization
      spellcheck:
        locale: US
      conventional:
        types:
          - feat
          - fix
          - dx
          - ci
          - docs
          - refactor
          - perf
          - test
          - chore
        scopes:
          - server
          - simulation
          - content
        descriptionLength: 72
